### ISSUE TITLE
How to use redirection options

### ISSUE THREAD

**Issue by nvermaa** [maxwroc/UrlEditorPro#194]
Hello,

I need help in using this app
![Screenshot 2021-12-07 12 57 47 PM](https://user-images.githubusercontent.com/95677158/144985183-c0600f4c-9f3e-45a6-9eeb-72b679eb662a.png)

I want to replace this URL
https://hume.google.com/graph/source?target=**topicserver.prod**&process=yt-music&id=%2Fauthority%2Fgoogle%2Fyoutube%2Fmusic%2Fa_da62ba05Rd4

to this URL
https://hume.google.com/graph/source?target=**composite.exp**&process=yt-music&id=%2Fauthority%2Fgoogle%2Fyoutube%2Fmusic%2Fa_da62ba05Rd4

Kindly let me know how to fill chrome-extension://maoigfcibanjdgnepaiiadjhgmejclea/options.html this to get above result

**Comment by maxwroc** [comment]
Sorry for lack of documentation. I have created this extension mainly for myself but since colleagues wanted it too I have shared it. 

First of all put the url which you want to change in the "Test url" field. This way tool will help you identify the problems and you will se the result url in the field below.

Second thing is to avoid creating automatic rules as they are being activated as soon as you try to access the url in the browser. So first experiment with the rule via context menu (when you go to the page with the matching address and right-click on extension icon you should see the redirect option there).

How it works exactly:
* First it is trying to match the navigation url (of the page you want to visit/go) with the filter.
* If there is a filter match then it applies the below updates
  * If you put something in the "Host name" it will replace the host name in the url
  * If you specify "Path" it will replace the path part of the url
  * And so on...

Url filter is only for the protocol, host and path. And it has to have wildcards.

Protocol is always at the beginning of the url e.g. http, https, ftp,... So it is not the host name part of the url (as on your screenshot)

The Params update section should be used in the following way: the first field should contain the param name and second its value. So in your case it would be setting `topicserver.prod` param with `composite.exp` value. So this is not something what you want to achieve. The better approach would be setting `target` in the first field and `composite.exp' in the other.

The best solution which I see in your case is to do the following:
![image](https://user-images.githubusercontent.com/8268674/145049916-a0d84ce0-20e8-494d-8c36-e112557909e6.png)

String replace works on the entire url content and can change any part of the url.

I hope thins helps

**Comment by nvermaa** [comment]
Thank You Maxwroc.

Your explanation was very detailed and helpful.
